pipeline {
	agent any

	tools {
		nodejs "nodejS"
	}

	stages {

        // 보안상 중요한 정보는 git에 저장하지 않았기 때문에 ec2=>컨테이너로 직접 복사
        stage("Set environment") {
            steps {
                echo "Copy require file to pipeline folder"
                sh 'cp /var/jenkins_home/util/frontend/.env ./frontend/dksl/.env'
            }
        }

		stage('React Build') {
			steps {
				dir('frontend/dksl') {
					sh 'npm install -g pnpm && pnpm install'
					sh 'pnpm build'
				}
			}
		}

		stage('Docker Build') {
			steps {
				dir('frontend/dksl') {
					sh 'docker build -t dksl_front:latest .'
				}
			}
		}

		stage('Deploy') {
			steps{
				sh 'docker rm -f front'
				sh 'docker run -d --name front -p 3126:3126 -u root	dksl_front:latest'
				}
		}

		stage('Finish') {
			steps{
				sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
			}
		}
	}
}